sudo: false

language: java
jdk:
  - oraclejdk8

install:
    - TERM=dumb ./gradlew --refresh-dependencies --stacktrace

script:
    - TERM=dumb ./gradlew build --stacktrace
  
after_failure:
  - "cat ./build/test-results/*.xml"

